### ISSUE TITLE
on python3.7 module 'statistics' has no attribute 'fmean'

### ISSUE THREAD

**Issue by kvbik** [pretalx/pretalx#1321]
## Current Behavior

on the `/review/` url we are getting this error
```
AttributeError: module 'statistics' has no attribute 'fmean'
```

## Expected Behavior

it should render page with results

## Context

this is an error of `statistics` module on python3.7, `pretalx` claims it works on py3.7 but thanks to this feature it does not!

## Your Environment

* Version used: `pretalx==2.3.1` but also `pretalx-dev`
* Environment name and version: `python3.7`
* Operating System and version (desktop or mobile): `ubuntu18.04`
* Link to your instance, if in production: https://speak.devcon.org/orga/

**Comment by rixx** [comment]
Fixed in 826e6c86, about two hours before the issue was opened!

**Comment by kvbik** [comment]
we've switched to py3.8 at the same time :D but wanted to leave a note for others :) big thanks for the fix!
